<?php
namespace moss\config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-16 at 21:59:22.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @dataProvider importProvider
     */
    public function testImportExport($result)
    {
        $default = array(
            'framework' => array(
                'error' => array('display' => true, 'level' => -1, 'detail' => true),
                'session' => array('name' => 'PHPSESSID', 'cacheLimiter' => ''),
                'cookie' => array('domain' => null, 'path' => '/', 'http' => true, 'ttl' => 2592000)
            ),
            'namespaces' => array(),
            'container' => array(),
            'dispatcher' => array(),
            'router' => array(),
        );
        $config = new Config();
        $config->import($result);
        $this->assertEquals(array_merge($default, $result), $config->export());
    }

    public function importProvider()
    {
        return array(
            array(
                array(
                    'framework' => array(
                        'error' => array('level' => E_ALL | E_NOTICE, 'detail' => true),
                        'session' => array('name' => 'PHPSESSID', 'cacheLimiter' => ''),
                        'cookie' => array('domain' => null, 'path' => '/', 'http' => true, 'ttl' => 2592000)
                    ),
                )
            ),
            array(
                array(
                    'namespaces' => array(),
                )
            ),
            array(
                array(
                    'container' => array(
                        'foo' => 'bar',
                        'component' => array(
                            'class' => '\stdClass',
                            'arguments' => array(),
                            'methods' => array(),
                            'shared' => false
                        )
                    ),
                )
            ),
            array(
                array(
                    'dispatcher' => array(
                        'foo' => array(
                            'component' => array(
                                'component' => 'foo',
                                'method' => array(),
                                'arguments' => array(),
                            )
                        )
                    ),
                )
            ),
            array(
                array(
                    'router' => array(
                        'routeName' => array(
                            'pattern' => '/{foo}/({bar})/',
                            'controller' => 'Moss:sample:Sample:index',
                            'requirements' => array(
                                'foo' => '\w+',
                                'bar' => '\w*'
                            ),
                            'defaults' => array(
                                'foo' => 'foo'
                            ),
                            'arguments' => array(
                                'locale' => 'pl',
                                'format' => 'json'
                            ),
                            'host' => null,
                            'schema' => null,
                            'methods' => array('GET', 'POST')
                        )
                    )
                )
            )
        );
    }

    /**
     * @expectedException \moss\config\ConfigException
     * @expectedExceptionMessage Missing required "component" or "closure" property in event listener definition
     */
    public function testInvalidDispatcherImport()
    {
        $result = array(
            'dispatcher' => array(
                'foo' => array(
                    'yada' => array()
                )
            )
        );

        $config = new Config();
        $config->import($result);
    }

    /**
     * @expectedException \moss\config\ConfigException
     * @expectedExceptionMessage Missing required "pattern" property in route definition
     */
    public function testInvalidRouterImportWithoutPattern()
    {
        $result = array(
            'router' => array(
                'routeName' => array(
                    'controller' => 'yada:yada'
                )
            )
        );

        $config = new Config();
        $config->import($result);
    }

    /**
     * @expectedException \moss\config\ConfigException
     * @expectedExceptionMessage Missing required "controller" property in route definition
     */
    public function testInvalidRouterImportWithoutController()
    {
        $result = array(
            'router' => array(
                'routeName' => array(
                    'pattern' => 'yada/yada'
                )
            )
        );

        $config = new Config();
        $config->import($result);
    }

    public function testGet()
    {
        $result = array(
            'level' => E_ALL | E_NOTICE,
            'detail' => true
        );

        $config = new Config(array('framework' => array('error' => $result)));
        $this->assertEquals($result, $config->get('framework.error'));
    }

    public function testGetDeep()
    {
        $config = new Config(array('framework' => array('error' => array('detail' => true))));
        $this->assertTrue($config->get('framework.error.detail'));
    }

    public function testGetBlank()
    {
        $config = new Config();
        $this->assertNull($config->get('foo'));
    }

    public function testGetDeepBlank()
    {
        $config = new Config();
        $this->assertNull($config->get('directories.foo'));
    }
}
