<?php
namespace Moss\config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-16 at 21:59:22.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var Config
	 */
	protected $object;

	protected function setUp() {
		$cArr = array(
			'framework' => array(
				'error' => array(
					'level' => E_ALL | E_NOTICE,
					'detail' => true
				),
				'session' => array(
					'host' => true,
					'ip' => true,
					'agent' => true,
					'salt' => null
				),
				'cookie' => array(
					'domain' => null,
					'path' => '/',
					'http' => true
				)
			)
		);

		$Config = new Config($cArr);
	}

	protected function tearDown() {
	}

	public function testGet() {
		$result = array(
			'level' => E_ALL | E_NOTICE,
			'detail' => true
		);

		$Config = new Config(array('framework' => array('error' => $result)));
		$this->assertEquals($result, $Config->get('framework.error'));
	}

	public function testGetDeep() {
		$Config = new Config(array('framework' => array('error' => array('detail' => true))));
		$this->assertTrue($Config->get('framework.error.detail'));
	}

	public function testGetBlank() {
		$Config = new Config();
		$this->assertNull($Config->get('foo'));
	}

	public function testGetDeepBlank() {
		$Config = new Config();
		$this->assertNull($Config->get('directories.foo'));
	}
}
