<?php
namespace Moss\config;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-16 at 21:59:22.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase {
	/**
	 * @var Config
	 */
	protected $object;

	protected function setUp() {
		$cArr = array(
			'error' => array(
				'level' => E_ALL | E_NOTICE,
				'detail' => true
			),
			'session' => array(
				'host' => true,
				'ip' => true,
				'agent' => true,
				'salt' => null
			)
		);

		$this->object = new Config($cArr);
	}

	protected function tearDown() {
	}

	public function testGet() {
		$result = array(
			'level' => E_ALL | E_NOTICE,
			'detail' => true
		);
		$this->assertEquals($result, $this->object->get('error'));
	}

	public function testGetDeep() {
		$this->assertTrue($this->object->get('error.detail'));
	}

	public function testGetBlank() {
		$this->assertNull($this->object->get('foo'));
	}

	public function testGetDeepBlank() {
		$this->assertNull($this->object->get('directories.foo'));
	}
}
